export const GETBALANCE = 'GETBALANCE';
export const GETLASTREPORTEDHASHRATE = 'GETLASTREPORTEDHASHRATE';
export const GETPRICINGHISTORYPERMINUTE = 'GETPRICINGHISTORYPERMINUTE';
export const GETWHATTOMINECRYPTOCURRENCYSTATUS = 'GETWHATTOMINECRYPTOCURRENCYSTATUS';
export const LOGINUSER = 'LOGINUSER';
export const GETMINERSTATUS = 'GETMINERSTATUS';